---
kind: Namespace
name: rxservice

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: rxservice

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: rxservice
  namespace: rxservice
spec:
  subscriptions:
  - image:
      discoveryLimit: 10
      repoURL: kargoacr.azurecr.io/nginx
      imageSelectionStrategy: SemVer
  - chart:
      repoURL: oci://kargoacr.azurecr.io/helm/rxservice
      semverConstraint: '>= 1.0.0'

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: rxservice
spec:
  subscriptions:
    warehouse: rxservice
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://git.innova-partners.com/cjohnson/argo-control.git
        insecureSkipTLSVerify: true # TODO: Trust CMM CA if we're using git.innova-partners.com
        writeBranch: main
        pullRequest: {}
        helm:
          charts:
          - repository: oci://kargoacr.azurecr.io/helm
            name: rxservice
            valuesFilePath: application-config/cmm-apps-staging/rxservice/values.yaml
          images:
          - image: kargoacr.azurecr.io/nginx
            key: 'rxservice.image.tag'
            value: Tag
            chartPath: application-config/cmm-apps-staging/rxservice
  verification:
    analysisTemplates:
      - name: analyze

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: release
  namespace: rxservice
spec:
  subscriptions:
    upstreamStages:
    - name: staging
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://git.innova-partners.com/cjohnson/argo-control.git
        insecureSkipTLSVerify: true # TODO: Trust CMM CA if we're using git.innova-partners.com
        writeBranch: main
        pullRequest: {}
        helm:
          images:
          - image: kargoacr.azurecr.io/nginx
            key: 'rxservice.image.tag'
            value: Tag
            valuesFilePath: application-config/cmm-apps-release/rxservice/values.yaml
          charts:
          - repository: oci://kargoacr.azurecr.io/helm
            name: rxservice
            chartPath: application-config/cmm-apps-release/rxservice
  verification:
    analysisTemplates:
      - name: analyze
