---
apiVersion: v1
kind: Namespace
metadata:
  name: rxservice
  labels:
    kargo.akuity.io/project: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: rxservice

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: rxservice
  namespace: rxservice
spec:
  subscriptions:
  - image:
      discoveryLimit: 10
      repoURL: kargoacr.azurecr.io/nginx
      imageSelectionStrategy: SemVer
  - chart:
      repoURL: oci://kargoacr.azurecr.io/helm/rxservice
      semverConstraint: '>= 1.0.0'

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: rxservice
spec:
  subscriptions:
    warehouse: rxservice
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://git.innova-partners.com/cjohnson/argo-control.git
        insecureSkipTLSVerify: true # TODO: Trust CMM CA if we're using git.innova-partners.com
        writeBranch: main
        pullRequest: {}
        helm:
          charts:
          - repository: oci://kargoacr.azurecr.io/helm
            name: rxservice
            chartPath: cmm-apps-staging/helm-chart-configs/rxservice
          images:
          - image: kargoacr.azurecr.io/nginx
            key: 'rxservice.image.tag'
            value: Tag
            valuesFilePath: cmm-apps-staging/helm-chart-configs/rxservice/values.yaml
  verification:
    analysisTemplates:
      - name: analyze

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: release
  namespace: rxservice
spec:
  subscriptions:
    upstreamStages:
    - name: staging
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://git.innova-partners.com/cjohnson/argo-control.git
        insecureSkipTLSVerify: true # TODO: Trust CMM CA if we're using git.innova-partners.com
        writeBranch: main
        pullRequest: {}
        helm:
          images:
          - image: kargoacr.azurecr.io/nginx
            key: 'rxservice.image.tag'
            value: Tag
            valuesFilePath: cmm-apps-release/helm-chart-configs/rxservice/values.yaml
          charts:
          - repository: oci://kargoacr.azurecr.io/helm
            name: rxservice
            chartPath: cmm-apps-release/helm-chart-configs/rxservice
  verification:
    analysisTemplates:
      - name: analyze

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: env5
  namespace: rxservice
spec:
  subscriptions:
    warehouse: rxservice
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://git.innova-partners.com/cjohnson/argo-control.git
        insecureSkipTLSVerify: true # TODO: Trust CMM CA if we're using git.innova-partners.com
        writeBranch: main
        pullRequest: {}
        helm:
          charts:
          - repository: oci://kargoacr.azurecr.io/helm
            name: rxservice
            chartPath: cmm-apps-env5/helm-chart-configs/rxservice
          images:
          - image: kargoacr.azurecr.io/nginx
            key: 'rxservice.image.tag'
            value: Tag
            valuesFilePath: cmm-apps-env5/helm-chart-configs/rxservice/values.yaml
  verification:
    analysisTemplates:
      - name: analyze
