apiVersion: v2
name: lava-demo-admin
description: A helm chart for deploying lava-demo-admin-database configured for lava-demo-cluster
type: application
version: 1.0.0
dependencies:
  - name: liquibase-helper
    version: 1.1.0
    repository: oci://mck-cmm-oci-prod-virtual.jfrog.io/covermymeds/helm
