liquibase-helper:
  databases:
    lava-demo-admin:
      image:
        repository: mck-cmm-oci-prod-virtual.jfrog.io/covermymeds/image/lava-demo-admin-database
        tag: 1.12.0
      secret:
        name: liquibase-credential
        urlKey: url
        usernameKey: username
        passwordKey: password
  liquibaseJob:
    args:
      - |
        liquibase update --changelog-file=changelog.yaml
        sleep 3600

secrets-helper:
  appSecrets:
    secrets:
      liquibase-credential:
        data:
          - targetSecretKey: url
            testingValue: jdbc:postgresql://cmm-dba-test.postgres.database.azure.com:5432/cmm_test
          - targetSecretKey: username
            testingValue: pgadmin
          - targetSecretKey: password
            testingValue: P@$$w0rd!
