apiVersion: v2
name: kargo
description: A helm chart for deploying kargo to cmm-platform-automation
type: application
version: 1.0.0
dependencies:
  - name: kargo
    repository: oci://ghcr.io/akuity/kargo-charts/kargo
    version: 0.7.0
